### ISSUE TITLE
GTNH 2.5.1 recipes for basic machines not textured

### ISSUE THREAD

**Issue by mbryantms** [Jimbno/Dark.UI#4]
![image](https://github.com/Jimbno/Dark.UI/assets/2883226/6b07d869-bf27-46d2-b649-5ea314ace9ed)

When looking up files in NEI and looking at recipes for basic machines like the macerator, or the centrifuge shown here, the main recipe section is not textured dark. This was tested with standard GTNH textures and no other resource packs.

**Comment by StaffiX** [comment]
missing `assets\gregtech\textures\gui\background\nei_single_recipe.png`

**Comment by Jimbno** [comment]
fixed finally

**Comment by Jimbno** [comment]
fixed
